// react-ui/src/components/Login.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import authService from '../services/authService'
import './Login.css'

function Login() {
  const [loginCreds, setLoginCreds] = useState({ email: '', password: '' })
  const [errorMessage, setErrorMessage] = useState('')
  const [errors, setErrors] = useState({ email: '', password: '' })
  const navigate = useNavigate()
  const { login } = useAuth()

  const validateField = (name, value) => {
    let error = ''
    if (!value) {
      error = `${name === 'email' ? 'Email' : 'Password'} is required`
    } else if (value.length < 2) {
      error = `${name === 'email' ? 'Email' : 'Password'} must be at least 2 characters long`
    }
    return error
  }

  const handleChange = (e) => {
    const { name, value } = e.target
    setLoginCreds(prev => ({ ...prev, [name]: value }))
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }))
    }
    setErrorMessage('')
  }

  const handleBlur = (e) => {
    const { name, value } = e.target
    const error = validateField(name, value)
    setErrors(prev => ({ ...prev, [name]: error }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    
    // Validate all fields
    const emailError = validateField('email', loginCreds.email)
    const passwordError = validateField('password', loginCreds.password)
    
    setErrors({
      email: emailError,
      password: passwordError
    })

    if (emailError || passwordError) {
      return
    }

    try {
      const response = await authService.loginUser(loginCreds)
      login(response.token)
      navigate('/home')
    } catch (error) {
      setErrorMessage(error)
    }
  }

  const isFormValid = loginCreds.email.length >= 2 && loginCreds.password.length >= 2

  return (
    <div className="container-fluid login-container">
      <div className="container xd-container">
        <h2>Welcome to Login</h2>
        <form onSubmit={handleSubmit} className="form-horizontal">
          <div className={`form-group has-feedback ${errors.email ? 'has-error' : loginCreds.email && !errors.email ? 'has-success' : ''}`}>
            <label htmlFor="email" className="col-sm-2 control-label">Email</label>
            <div className="col-sm-10">
              <input
                type="text"
                className="form-control"
                id="email"
                name="email"
                value={loginCreds.email}
                onChange={handleChange}
                onBlur={handleBlur}
                minLength="2"
                required
              />
              <span className={`glyphicon form-control-feedback ${errors.email ? 'glyphicon-remove' : loginCreds.email && !errors.email ? 'glyphicon-ok' : ''}`} aria-hidden="true"></span>
              {errors.email && <span className="help-block">{errors.email}</span>}
            </div>
          </div>
          
          <div className={`form-group has-feedback ${errors.password ? 'has-error' : loginCreds.password && !errors.password ? 'has-success' : ''}`}>
            <label htmlFor="password" className="col-sm-2 control-label">Password</label>
            <div className="col-sm-10">
              <input
                type="password"
                className="form-control"
                id="password"
                name="password"
                value={loginCreds.password}
                onChange={handleChange}
                onBlur={handleBlur}
                minLength="2"
                required
              />
              <span className={`glyphicon form-control-feedback ${errors.password ? 'glyphicon-remove' : loginCreds.password && !errors.password ? 'glyphicon-ok' : ''}`} aria-hidden="true"></span>
              {errors.password && <span className="help-block">{errors.password}</span>}
            </div>
          </div>

          {errorMessage && (
            <div className="form-group">
              <div className="col-sm-offset-2 col-sm-10">
                <div className="alert alert-danger" role="alert">
                  {errorMessage}
                </div>
              </div>
            </div>
          )}

          <div className="form-group">
            <div className="col-sm-offset-2 col-sm-10">
              <button className="btn btn-default" type="submit" disabled={!isFormValid}>
                Sign In
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}

export default Login

// angular-ui/src/app/auth/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import { AuthService } from '../auth.service';
import { CookieService } from 'ngx-cookie-service';
import { LoginCreds } from './login-creds';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  loginCreds: LoginCreds;
  errorMessage: string;

  constructor(private authService: AuthService, private cookieService: CookieService,
     private router: Router) {
    this.loginCreds = {} as LoginCreds;
  }

  ngOnInit() {
  }

  onSubmit(loginCreds: LoginCreds) {
    this.authService.loginUser(loginCreds).subscribe(
      response => {
        this.cookieService.set('token', response.token);
        this.authService.isAuthenticated = true;
        this.goToHomePage();
      },
      error => this.errorMessage = error as any
    );
  }

  goToHomePage() {
    this.router.navigate(['welcome']);
  }

}

<!--
  ~ /*
  ~  * Copyright 2016-2017 the original author or authors.
  ~  *
  ~  * Licensed under the Apache License, Version 2.0 (the "License");
  ~  * you may not use this file except in compliance with the License.
  ~  * You may obtain a copy of the License at
  ~  *
  ~  *      http://www.apache.org/licenses/LICENSE-2.0
  ~  *
  ~  * Unless required by applicable law or agreed to in writing, software
  ~  * distributed under the License is distributed on an "AS IS" BASIS,
  ~  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  * See the License for the specific language governing permissions and
  ~  * limitations under the License.
  ~  */
  -->



<div class="container-fluid">
  <div class="container xd-container">
    <h2>
      Login
    </h2>
    <form (ngSubmit)="onSubmit(loginForm.value)" #loginForm="ngForm" class="form-horizontal">
      <div class="form-group has-feedback" [class.has-success]="email.dirty && email.valid" [class.has-error]="email.dirty &&  !email.valid">
        <label for="email" class="col-sm-2 control-label">email</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="email" [(ngModel)]="loginCreds.email" minlength="2" required name="email" #email="ngModel"/>
          <span class="glyphicon form-control-feedback" [class.glyphicon-ok]="email.valid" [class.glyphicon-remove]="!email.valid" aria-hidden="true"></span>
          <span class="help-block" *ngIf="email.dirty && email.hasError('required')">email is required</span>
          <span class="help-block" *ngIf="email.dirty && email.hasError('minlength')">email must be at least 2 characters long</span>
        </div>
      </div>
      <div class="form-group has-feedback" [class.has-success]="password.dirty && password.valid" [class.has-error]="password.dirty && !password.valid">
        <label for="password" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="password" [(ngModel)]="loginCreds.password" name="password" minlength="2" required #password="ngModel"/>
          <span class="glyphicon form-control-feedback" [class.glyphicon-ok]="password.valid" [class.glyphicon-remove]="!password.valid" aria-hidden="true"></span>
          <span class="help-block" *ngIf="password.dirty && password.hasError('required')">Password is required</span>
          <span class="help-block" *ngIf="password.dirty && password.hasError('minlength')">Password must be at least 2 characters long</span>
        </div>
      </div>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button class="btn btn-default" type="submit" [disabled]="!loginForm.valid">Sign In</button>
        </div>
      </div>
    </form>
  </div>
</div>
